### ISSUE TITLE
expireInSeconds overrides Cache-Control directive of response

### ISSUE THREAD

**Issue by Toflar** [litespeedtech/openlitespeed#126]
**Description**
OLS just overrides my `Cache-Control` directive which I think is wrong if I configure `ignoreRespCacheCtrl 0`.

**Reproducible case**
Configure `expireInSeconds 10` and set `Cache-Control: max-age=60` on the response.

**What is expected**
Miss on the first request, then hit for 60 seconds.

**What happens instead**
Miss on the first request, then hit only for 10 seconds.

In general, I expect OLS not to interfere with my response expiration settings at all if I configure `ignoreRespCacheCtrl 0`. `expireInSeconds` should only be considered if `ignoreRespCacheCtrl 1`.

**Comment by litespeedtech** [comment]
We discussed  and this is not a bug.
Because the module config is higher priority than the normal cache-control, but "X-Litespeed-Cache-Control" has the most higher priority. Usually the back-end will always give the shorter cache length.
But we can do some update, such as to check this "Cache-Control: max-age=60" and choose the longer time as the expire time for this url cache. Do you think this is better?

**Comment by Toflar** [comment]
> Do you think this is better?

No, not really. What I'd like to have is to tell the cache module to not fiddle around with my responses **at all**.
Maybe you could introduce that if `expireInSeconds 0` then that means the configuration is disabled and thus only `Cache-Control` is considered.
Otherwise I have to set `expireInSeconds` to `9999999999999` because I never want it to override anything from my module configuration.

**Comment by litespeedtech** [comment]
OK. I can do this.
Thanks.

**Comment by Toflar** [comment]
Afaik this has been fixed in https://github.com/litespeedtech/openlitespeed/commit/25bce60d1a981e72948be38b8ded46caca114be4 right?

**Comment by litespeedtech** [comment]
So this is implemented in the current released version.
Thanks.
