### ISSUE TITLE
Arch Linux pre-built binary

### ISSUE THREAD

**Issue by HLFH** [litespeedtech/openlitespeed#361]
Currently, only CentOS, Debian and Ubuntu binaries are provided.
No Arch Linux binary is provided or supported for x86_64 arch.

**Comment by HLFH** [comment]
Therefore, I am requesting the deletion of [`openlitespeed-bin` on Arch Linux](https://aur.archlinux.org/packages/openlitespeed-bin).
Keep me posted when Arch Linux binary in x86_64 arch is provided / supported.

**Comment by lighth7015** [comment]
Manjaro user here.

Good sir, are you aware that the AUR is ArchLinux USERS providing and supporting packages directly? It's, "_I run arch, and need X package- but I can't find it in the core or community repository, so I'll do it myself._"

A package existing in the AUR is *not* "_no binary available_" -- it's, "_Unfortunately, you'll have to build the package yourself if you want a binary, because not enough of our userbase wants this package, and none of the trusted users presently want to sponsor the package for it to make its way into the community repository._" -- you're supposed to work with the AUR package's maintainer in order to ensure that everybody can build the package.

This PR robs all of us Arch (and derivatives) users of the opportunity to install and run OLS on their systems, especially if the project itself doesn't have the time, resources or interest of supporting Arch distributions (and derivatives).

I humbly request this issue decision be reversed, and that the package be allowed to exist as in the AUR, and hopefully one day it'll get the chance to make its way into the `community` repository; this way everybody wins- OLS gets to exist in more distros and us Arch users get to run OLS 😁 

I'm tired of all the interesting web servers (_e.g., OLS_, _Caddy_, et al) not being able to run on Arch natively.

Anyway, this is just my two cents, as I just stumbled across this issue, and it made me sad, so I had to comment on it, even though it's closed!
