### ISSUE TITLE
Documentation: Lack of ESI Support Causes issues with WordPress Nonces

### ISSUE THREAD

**Issue by jordantrizz** [litespeedtech/openlitespeed#372]
From what I found, there's nowhere talking about [WordPress Nonces](https://codex.wordpress.org/WordPress_Nonces) and Openlitespeed. Please correct anything inaccurate in this issue, that's why I'm creating it.

So I'm creating this issue to bring more attention to the fact that WordPress nonce can't be cached with Openlitespeed using the WordPress LSCache plugin since Openlitespeed doesn't support ESI. 

Litespeed Enterprise is different due to the support of ESI and support within the LSCache plugin to cache WordPress Nonces using ESI.

The only resource I found searching was this forum post https://forum.openlitespeed.org/threads/wp-nonce-is-cached.4512/

There should be further documentation about Openlitespeed and WordPress Nonces. A step further would be to enable ESI within Openlitespeed, as this would push more usage versus Nginx.

**Comment by litespeedtech** [comment]
LiteSpeed WordPress cache plugin should detect and automatically disable nonce caching when ESI support is absent. 
We will improve the documentation. Thanks for the remainder.

**Comment by jordantrizz** [comment]
> LiteSpeed WordPress cache plugin should detect and automatically disable nonce caching when ESI support is absent.
> We will improve the documentation. Thanks for the remainder.

That's not really what I was concerned about. If this does happen, and the Litespeed Cache TTL is set to over 12 hours then WordPress Nonces fail to work. Instead, there should be detection within LSCache to detect ESI is not available, and when the Cache TTL is higher than 12 hours and add a warning.

**Comment by jordantrizz** [comment]
> Does seem that Gravity Forms loads in nonces using Ajax

This is how you should implement nonces so they're not cached. 

I don't see anything on about nonces being detect on the fly in this document https://docs.litespeedtech.com/lscache/lscwp/thirdparty/

**Comment by lslisa** [comment]
For the record, I did check the documentation at the time of this original issue, and noted that there was already a warning there that OLS doesn't support ESI. I rephrased the warning to make it more clear. 

I can't speak to the WordPress plugin side of things--I'll leave that for my colleagues--but I wanted to let you know that the original docs issue _was_ reviewed right away.

This issue was closed after @litespeedtech said we'd update the docs, so if you still have questions, it would probably be a good idea to re-open the issue so it gets reviewed.
